Add requirements
conda-forge/ligo-asimov-feedstock pull request #1
Opened 2021-05-25 16:33 UTC by duncanmmacleod

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2021-05-25 16:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-05-25 20:21 UTC, transientlunatic commented on recipe/meta.yaml
>    doc_url: https://daniel-williams.docs.ligo.org/supervisor/
Now at https://asimov.docs.ligo.org/asimov/

2021-05-25 20:22 UTC, transientlunatic commented on recipe/meta.yaml
>    dev_url: https://github.com/transientlunatic/asimov
Now at https://git.ligo.org/asimov/asimov

2021-05-25 20:25 UTC, transientlunatic requested changes
We should update to v0.3.0 while making these changes, and update the documentation and repository locations (I've added these in comments).
Otherwise, thanks for putting this together!

2021-05-26 09:40 UTC, duncanmmacleod commented
> We should update to v0.3.0 while making these changes, and update the documentation and repository locations (I've added these in comments).
> Otherwise, thanks for putting this together!

The version here tracks the 'upstream' releases on https://pypi.org/project/ligo-asimov/ which only sees 0.2.0. Do you have plans to upload new release tarballs there, or should we track the gitlab repo?

2021-06-03 09:19 UTC, closed without merging